# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  uos:
    runs-on: ubuntu-latest
    container: 
      image: tonquer/deepin-python:v20
      options: --privileged
    env:
      PACKAGENAME: jmcomic_py310_uos
    steps:
    - name: Add custom bin to PATH
      run: |
          echo "/root/.pyenv/plugins/pyenv-virtualenv/shims:/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" > $GITHUB_PATH
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: |
        source /root/.bashrc 
        ls -lh /root/.pyenv/versions/
        pyenv global 3.10.21
        python3 -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r src/requirements.txt
    - name: Build
      run: |
        python3 script/build_qrc.py
        cd src
        pyinstaller --hidden-import=_cffi_backend --collect-all curl_cffi  -w start.py
        cd dist
        mkdir -p jmcomic.AppRun/usr/bin
        cp -r ../../res/appimage/* jmcomic.AppRun/
        cp -r ../../res/icon/logo_round.png jmcomic.AppRun/JMComic.png
        cp -r start/* jmcomic.AppRun/usr/bin/

        chmod +x jmcomic.AppRun/AppRun
        chmod +x jmcomic.AppRun/usr/bin/start
        appimagetool-x86_64.AppImage jmcomic.AppRun
        mv JMComic-x86_64.AppImage ../../${{ env.PACKAGENAME }}-x86_64.AppImage
        cd ../..
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}-x86_64.AppImage
        retention-days: 7
